// utils/fileProcessing.ts - 헤더 감지 약화 및 원본 구조 완전 보존 버전
import * as XLSX from 'xlsx';

// ============================================================================
// 상태 관리 인터페이스 확장 (기존 코드와 호환성 유지)
// ============================================================================

// 기존 SheetData 인터페이스 확장
export interface ExtendedSheetData {
  sheetName: string;
  headers: string[]; // 기존 호환성 유지
  data: string[][]; // 기존 호환성 유지
  rawData: string[][]; // 완전한 원본 데이터
  
  // 새로 추가된 상세 정보
  headerInfo: {
    headerRow: number; // 실제 헤더가 위치한 행 (없으면 -1)
    headerDetails: Array<{
      name: string;
      originalColumn: number;
      columnLetter: string;
    }>;
    headerPositions: { [originalCol: number]: number };
    isAutoGenerated?: boolean; // 헤더가 자동 생성되었는지 여부
  };
  
  dataBounds: {
    minRow: number;
    maxRow: number;
    minCol: number;
    maxCol: number;
    actualStartRow: number; // 실제 데이터 시작 행
    actualStartCol: number; // 실제 데이터 시작 열
  };
  
  metadata?: {
    rowCount: number;
    columnCount: number;
    headerRow: number;
    headerRowData?: string[];
    headerMap?: { [index: number]: number };
    dataRange: {
      startRow: number;
      endRow: number;
      startCol: number;
      endCol: number;
      startColLetter: string;
      endColLetter: string;
    };
    preserveOriginalStructure?: boolean;
    lastModified?: Date;
    // 새로 추가된 원본 구조 정보
    originalHeaderRow?: number;
    originalDataBounds?: {
      minRow: number;
      maxRow: number;
      minCol: number;
      maxCol: number;
      actualStartRow: number;
      actualStartCol: number;
    };
    headerDetails?: Array<{
      name: string;
      originalColumn: number;
      columnLetter: string;
    }>;
  };
}

// ============================================================================
// 핵심 유틸리티 함수들
// ============================================================================

// 첫 번째 비어있지 않은 셀을 찾는 함수
export const findFirstNonEmptyCell = (data: string[][]): { row: number; col: number } => {
  for (let row = 0; row < data.length; row++) {
    if (!data[row]) continue;
    for (let col = 0; col < data[row].length; col++) {
      if (data[row][col] && data[row][col].toString().trim() !== '') {
        return { row, col };
      }
    }
  }
  return { row: 0, col: 0 };
};

// 헤더 행을 찾는 함수 - 약화된 버전
export const findHeaderRow = (data: string[][], startRow: number = 0): number => {
  // 빈 데이터인 경우
  if (!data || data.length === 0) {
    return -1;
  }

  let bestHeaderRow = -1;
  let bestScore = 0;
  
  // 처음 10행 내에서만 헤더 찾기 시도
  for (let row = startRow; row < Math.min(data.length, startRow + 10); row++) {
    if (!data[row]) continue;
    
    let nonEmptyCount = 0;
    let consecutiveNonEmpty = 0;
    let maxConsecutive = 0;
    
    for (let col = 0; col < data[row].length; col++) {
      const cellValue = data[row][col];
      const cellStr = cellValue ? cellValue.toString().trim() : '';
      
      if (cellStr !== '') {
        nonEmptyCount++;
        consecutiveNonEmpty++;
        maxConsecutive = Math.max(maxConsecutive, consecutiveNonEmpty);
      } else {
        consecutiveNonEmpty = 0;
      }
    }
    
    // 매우 관대한 헤더 점수 계산 - 연속된 셀이 2개 이상이면 헤더 후보
    const score = maxConsecutive;
    
    if (maxConsecutive >= 2 && score > bestScore) {
      bestScore = score;
      bestHeaderRow = row;
    }
  }
  
  // 헤더를 찾지 못한 경우 -1 반환 (에러가 아님)
  return bestHeaderRow;
};

// 실제 데이터 범위를 찾는 함수
export const findActualDataBounds = (data: string[][]): {
  minRow: number;
  maxRow: number;
  minCol: number;
  maxCol: number;
} => {
  let minRow = data.length;
  let maxRow = -1;
  let minCol = Number.MAX_SAFE_INTEGER;
  let maxCol = -1;
  
  for (let row = 0; row < data.length; row++) {
    if (!data[row]) continue;
    
    let hasData = false;
    for (let col = 0; col < data[row].length; col++) {
      const cellValue = data[row][col];
      if (cellValue && cellValue.toString().trim() !== '') {
        hasData = true;
        minCol = Math.min(minCol, col);
        maxCol = Math.max(maxCol, col);
      }
    }
    
    if (hasData) {
      minRow = Math.min(minRow, row);
      maxRow = Math.max(maxRow, row);
    }
  }
  
  // 데이터가 없는 경우 기본값 반환
  if (maxRow === -1) {
    return { minRow: 0, maxRow: 0, minCol: 0, maxCol: 0 };
  }
  
  return { minRow, maxRow, minCol, maxCol };
};

// 자동으로 헤더 생성하는 함수
export const generateAutoHeaders = (colCount: number, startCol: number = 0): Array<{
  name: string;
  originalColumn: number;
  columnLetter: string;
}> => {
  const headers: Array<{
    name: string;
    originalColumn: number;
    columnLetter: string;
  }> = [];
  
  for (let i = 0; i < colCount; i++) {
    const colIndex = startCol + i;
    const colLetter = columnIndexToLetter(colIndex);
    headers.push({
      name: `Column ${colLetter}`,
      originalColumn: colIndex,
      columnLetter: colLetter
    });
  }
  
  return headers;
};

// 헤더 정보 추출 - 원본 위치 정보 포함 (헤더가 없을 경우 자동 생성)
export const extractHeaderInfo = (
  data: string[][], 
  headerRowIndex: number,
  dataBounds: { minCol: number; maxCol: number }
): {
  headers: Array<{
    name: string;
    originalColumn: number;
    columnLetter: string;
  }>;
  headerPositions: { [originalCol: number]: number };
  isAutoGenerated: boolean;
} => {
  // 헤더가 없는 경우 자동 생성
  if (headerRowIndex === -1 || !data[headerRowIndex]) {
    const colCount = dataBounds.maxCol - dataBounds.minCol + 1;
    const autoHeaders = generateAutoHeaders(colCount, dataBounds.minCol);
    
    const headerPositions: { [originalCol: number]: number } = {};
    autoHeaders.forEach((header, index) => {
      headerPositions[header.originalColumn] = index;
    });
    
    return {
      headers: autoHeaders,
      headerPositions,
      isAutoGenerated: true
    };
  }
  
  // 기존 헤더 추출 로직
  const headers: Array<{
    name: string;
    originalColumn: number;
    columnLetter: string;
  }> = [];
  
  const headerPositions: { [originalCol: number]: number } = {};
  const headerRow = data[headerRowIndex];
  
  // 데이터 범위 내의 모든 열에 대해 헤더 생성
  for (let col = dataBounds.minCol; col <= dataBounds.maxCol; col++) {
    const headerValue = headerRow[col];
    const headerStr = String(headerValue || '').trim();
    
    const headerIndex = headers.length;
    headerPositions[col] = headerIndex;
    
    // 빈 헤더는 자동으로 이름 생성
    const headerName = headerStr || `Column ${columnIndexToLetter(col)}`;
    
    headers.push({
      name: headerName,
      originalColumn: col,
      columnLetter: columnIndexToLetter(col)
    });
  }
  
  return { headers, headerPositions, isAutoGenerated: false };
};

// 열 인덱스를 엑셀 열 이름으로 변환
export const columnIndexToLetter = (index: number): string => {
  let result = '';
  while (index >= 0) {
    result = String.fromCharCode(65 + (index % 26)) + result;
    index = Math.floor(index / 26) - 1;
  }
  return result;
};

// 엑셀 열 이름을 인덱스로 변환
export const columnLetterToIndex = (letter: string): number => {
  let result = 0;
  for (let i = 0; i < letter.length; i++) {
    result = result * 26 + (letter.charCodeAt(i) - 64);
  }
  return result - 1;
};

// ============================================================================
// 파일 처리 메인 함수들
// ============================================================================

// XLSX 파일 처리 함수 - 헤더 감지 약화 및 원본 구조 완전 보존 버전
export const processXLSXFile = async (file: File): Promise<{
  sheets: Array<ExtendedSheetData>;
  fileName: string;
}> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    
    reader.onload = (e) => {
      try {
        const data = new Uint8Array(e.target?.result as ArrayBuffer);
        const workbook = XLSX.read(data, { 
          type: 'array',
          cellFormula: true, // 수식 보존
          cellStyles: true,  // 스타일 보존
          cellDates: true,   // 날짜 보존
          sheetStubs: true,  // 빈 셀도 포함
          raw: false         // 포맷된 값 사용
        });
        
        const processedSheets: ExtendedSheetData[] = workbook.SheetNames.map(sheetName => {
          console.log(`Processing sheet: ${sheetName}`);
          const worksheet = workbook.Sheets[sheetName];
          
          // 워크시트의 범위 정보 가져오기
          const range = XLSX.utils.decode_range(worksheet['!ref'] || 'A1');
          
          // 원본 데이터 추출 - 완전한 원본 구조 유지
          const rawData = XLSX.utils.sheet_to_json(worksheet, { 
            header: 1,
            defval: '', // 빈 셀을 빈 문자열로 처리
            raw: false, // 포맷된 값 사용
            blankrows: true, // 빈 행 유지
            range: worksheet['!ref'] // 전체 범위 사용
          }) as string[][];
          
          console.log(`Raw data dimensions for ${sheetName}: ${rawData.length} rows, range: ${worksheet['!ref']}`);
          
          // 완전히 빈 시트 처리
          const hasAnyData = rawData.some(row => 
            row && row.some(cell => cell && cell.toString().trim() !== '')
          );
          
          if (!hasAnyData) {
            console.log(`Sheet ${sheetName} is completely empty`);
            return {
              sheetName,
              rawData: [[]],
              headers: [],
              data: [],
              headerInfo: {
                headerRow: -1,
                headerDetails: [],
                headerPositions: {},
                isAutoGenerated: true
              },
              dataBounds: {
                minRow: 0, maxRow: 0, minCol: 0, maxCol: 0,
                actualStartRow: 0, actualStartCol: 0
              },
              metadata: {
                headerRow: -1,
                rowCount: 0,
                columnCount: 0,
                dataRange: {
                  startRow: 0, endRow: 0, startCol: 0, endCol: 0,
                  startColLetter: 'A', endColLetter: 'A'
                },
                preserveOriginalStructure: true,
                lastModified: new Date()
              }
            };
          }
          
          // 실제 데이터 범위 찾기
          const dataBounds = findActualDataBounds(rawData);
          console.log(`Data bounds for ${sheetName}:`, dataBounds);
          
          // 헤더 행 찾기 (못 찾아도 OK)
          const headerRowIndex = findHeaderRow(rawData, dataBounds.minRow);
          console.log(`Header row for ${sheetName}: ${headerRowIndex} (${headerRowIndex === -1 ? 'not found, will auto-generate' : 'found'})`);
          
          // 헤더 정보 추출 (없으면 자동 생성)
          const { headers: headerDetails, headerPositions, isAutoGenerated } = 
            extractHeaderInfo(rawData, headerRowIndex, dataBounds);
          
          console.log(`Headers for ${sheetName} (${isAutoGenerated ? 'auto-generated' : 'detected'}):`, 
            headerDetails.map(h => `${h.name}(${h.columnLetter})`));
          
          // 기존 호환성을 위한 단순한 배열 생성
          const simpleHeaders = headerDetails.map(h => h.name);
          
          // 데이터 시작 행 결정
          const dataStartRow = headerRowIndex === -1 
            ? dataBounds.minRow // 헤더가 없으면 첫 데이터 행부터
            : Math.max(headerRowIndex + 1, dataBounds.minRow); // 헤더 다음 행부터
          
          // 기존 호환성을 위한 데이터 배열 생성
          const processedData: string[][] = [];
          
          for (let row = dataStartRow; row <= dataBounds.maxRow; row++) {
            if (!rawData[row]) continue;
            
            const dataRow: string[] = [];
            headerDetails.forEach(headerInfo => {
              const cellValue = rawData[row][headerInfo.originalColumn] || '';
              dataRow.push(String(cellValue));
            });
            
            // 모든 행을 추가 (빈 행도 포함하여 원본 구조 유지)
            processedData.push(dataRow);
          }
          
          console.log(`Processed ${processedData.length} data rows for ${sheetName}`);
          
          const result: ExtendedSheetData = {
            sheetName,
            rawData, // 완전한 원본 보존
            headers: simpleHeaders, // 기존 호환성
            data: processedData, // 기존 호환성
            headerInfo: {
              headerRow: headerRowIndex,
              headerDetails,
              headerPositions,
              isAutoGenerated
            },
            dataBounds: {
              ...dataBounds,
              actualStartRow: dataStartRow,
              actualStartCol: dataBounds.minCol
            },
            metadata: {
              headerRow: headerRowIndex,
              headerRowData: headerRowIndex !== -1 ? rawData[headerRowIndex] : undefined,
              headerMap: headerPositions,
              rowCount: processedData.length,
              columnCount: simpleHeaders.length,
              dataRange: {
                startRow: dataStartRow,
                endRow: dataBounds.maxRow,
                startCol: dataBounds.minCol,
                endCol: dataBounds.maxCol,
                startColLetter: columnIndexToLetter(dataBounds.minCol),
                endColLetter: columnIndexToLetter(dataBounds.maxCol)
              },
              preserveOriginalStructure: true,
              lastModified: new Date(),
              // 새로 추가된 원본 구조 정보
              originalHeaderRow: headerRowIndex,
              originalDataBounds: {
                ...dataBounds,
                actualStartRow: dataStartRow,
                actualStartCol: dataBounds.minCol
              },
              headerDetails
            }
          };
          
          return result;
        });
        
        // 완전히 빈 시트를 제외하고 반환
        const nonEmptySheets = processedSheets.filter(sheet => 
          sheet.rawData.length > 1 || // 여러 행이 있거나
          (sheet.rawData.length === 1 && sheet.rawData[0].length > 0 && sheet.rawData[0].some(cell => cell !== '')) // 데이터가 있는 경우
        );
        
        console.log(`Successfully processed ${nonEmptySheets.length} non-empty sheets from ${file.name}`);
        
        resolve({
          sheets: nonEmptySheets.length > 0 ? nonEmptySheets : processedSheets, // 모든 시트가 비어있어도 최소 1개는 반환
          fileName: file.name
        });
      } catch (error) {
        console.error('XLSX 파일 처리 오류:', error);
        reject(error);
      }
    };
    
    reader.onerror = () => reject(new Error('파일 읽기 실패'));
    reader.readAsArrayBuffer(file);
  });
};

// 디버깅을 위한 시트 정보 출력
export const debugSheetInfo = (sheetData: ExtendedSheetData): void => {
  console.group(`📊 Sheet Debug Info: ${sheetData.sheetName}`);
  console.log('📐 Raw Data Dimensions:', `${sheetData.rawData.length} rows × ${sheetData.rawData[0]?.length || 0} cols`);
  console.log('📍 Header Row:', sheetData.headerInfo.headerRow, sheetData.headerInfo.isAutoGenerated ? '(auto-generated)' : '(detected)');
  console.log('🏷️ Headers:', sheetData.headerInfo.headerDetails.map(h => `${h.name}(${h.columnLetter})`));
  console.log('📊 Data Bounds:', sheetData.dataBounds);
  console.log('📋 Processed Data:', `${sheetData.data.length} rows × ${sheetData.headers.length} cols`);
  
  // 샘플 데이터 출력 (처음 3행)
  if (sheetData.data.length > 0) {
    console.log('📝 Sample Data:');
    console.table(sheetData.data.slice(0, 3));
  }
  
  console.groupEnd();
};

// 나머지 함수들은 그대로 유지...
export const findDataRange = (rawData: string[][], headerRow: number) => {
  const headerRowData = rawData[headerRow] || [];
  const dataBounds = findActualDataBounds(rawData);
  
  // 헤더가 없는 경우를 위한 처리
  if (headerRow === -1) {
    const { headers, headerPositions } = extractHeaderInfo(rawData, -1, dataBounds);
    
    return {
      headerRowData: headers.map(h => h.name),
      validHeaders: headers.map(h => h.name),
      headerMap: headerPositions,
      maxRow: dataBounds.maxRow,
      maxCol: dataBounds.maxCol
    };
  }
  
  // 기존 로직
  const validHeaders: string[] = [];
  const headerMap: { [key: number]: number } = {};
  
  headerRowData.forEach((header, index) => {
    if (header && String(header).trim() !== '') {
      headerMap[index] = validHeaders.length;
      validHeaders.push(String(header).trim());
    }
  });
  
  return {
    headerRowData,
    validHeaders,
    headerMap,
    maxRow: dataBounds.maxRow,
    maxCol: dataBounds.maxCol
  };
};